import './globals.css'
import { Inter } from 'next/font/google'
import Providers from "./providers"
import ThemeSwitch from '@/components/ThemeSwitch'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <body className="${inter.className} bg-white dark:bg-[#111010]"><Providers>{children}</Providers></body>
      </head>
    </html>
  )
}
